services:
  # FastAPI Web Service
  - type: web
    name: librarity-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: librarity-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: librarity-redis
          type: redis
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    
  # Celery Worker Service
  - type: worker
    name: librarity-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A workers.celery_app worker --loglevel=info --pool=solo --concurrency=1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: librarity-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: librarity-redis
          type: redis
          property: connectionString

databases:
  - name: librarity-db
    databaseName: librarity
    plan: starter

  - name: librarity-redis
    plan: starter
